
import javax.swing.Icon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author angel
 */
public class Dados_Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Dados_Interfaz
     */
    public Dados_Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn_Tiralosdados = new javax.swing.JButton();
        LblDado1 = new javax.swing.JLabel();
        LblDado2 = new javax.swing.JLabel();
        jTxt1 = new javax.swing.JTextField();
        BtnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Btn_Tiralosdados.setBackground(new java.awt.Color(51, 153, 255));
        Btn_Tiralosdados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn_Tiralosdados.setText("Tira los Dados");
        Btn_Tiralosdados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TiralosdadosActionPerformed(evt);
            }
        });

        LblDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/Cuatro.png"))); // NOI18N

        LblDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/Seis.png"))); // NOI18N

        jTxt1.setEditable(false);
        jTxt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt1ActionPerformed(evt);
            }
        });

        BtnMenu.setText("Menú");
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblDado2))
                            .addComponent(Btn_Tiralosdados, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(BtnMenu)
                        .addGap(50, 50, 50)
                        .addComponent(jTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Btn_Tiralosdados, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(LblDado2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(LblDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMenu))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt1ActionPerformed
        
    }//GEN-LAST:event_jTxt1ActionPerformed

    private void Btn_TiralosdadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TiralosdadosActionPerformed
        /// Generaremos el tiro de los dados y usaremos numeros de manera aleatoria
        int dado1 = (int)(Math.random()*6)+1;
        int dado2 = (int)(Math.random()*6)+1;
        
        //Generacion de iconos 
        Icon uno = new javax.swing.ImageIcon(getClass().getResource("/Dados/Uno.png"));
        Icon dos = new javax.swing.ImageIcon(getClass().getResource("/Dados/Dos.png"));
        Icon tres = new javax.swing.ImageIcon(getClass().getResource("/Dados/Tres.png"));
        Icon cuatro = new javax.swing.ImageIcon(getClass().getResource("/Dados/Cuatro.png"));
        Icon cinco = new javax.swing.ImageIcon(getClass().getResource("/Dados/Cinco.png"));
        Icon seis = new javax.swing.ImageIcon(getClass().getResource("/Dados/Seis.png"));
             
        switch(dado1){
            case 1: LblDado1.setIcon(uno); break;
            case 2: LblDado1.setIcon(dos); break;
            case 3: LblDado1.setIcon(tres); break;
            case 4: LblDado1.setIcon(cuatro); break;
            case 5: LblDado1.setIcon(cinco); break;
            case 6: LblDado1.setIcon(seis); break;
        }
        
        switch(dado2){
            case 1: LblDado2.setIcon(uno); break;
            case 2: LblDado2.setIcon(dos); break;
            case 3: LblDado2.setIcon(tres); break;
            case 4: LblDado2.setIcon(cuatro); break;
            case 5: LblDado2.setIcon(cinco); break;
            case 6: LblDado2.setIcon(seis); break;
        }
        
        int resultado = dado1 + dado2;
        jTxt1.setText("Te salio!!!: " + resultado);
        
    }//GEN-LAST:event_Btn_TiralosdadosActionPerformed

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        Menu opcion = new Menu();
        opcion.setVisible(true);
        this.setVisible (false);
    }//GEN-LAST:event_BtnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dados_Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton Btn_Tiralosdados;
    private javax.swing.JLabel LblDado1;
    private javax.swing.JLabel LblDado2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxt1;
    // End of variables declaration//GEN-END:variables
}
